package fr.univlr.cri.conges;
// Generated by the WOLips TemplateEngine Plug-in at 19 sept. 2005 14:48:37

import com.webobjects.appserver.*;

import fr.univlr.cri.webapp.CRIWebComponent;

public class CngAvertissement extends CRIWebComponent {

  public CngAvertissement(WOContext context) {
    super(context);
  }

}