package fr.univlr.cri.conges;
// Generated by the WOLips TemplateEngine Plug-in at 17 mars 2006 11:36:50

import com.webobjects.appserver.*;

/**
 * Composant permettant d'afficher un message d'information
 * @author Cyril TARADE <cyril.tarade at univ-lr.fr>
 */

public class CngInfoBox extends WOComponent {
  
  public CngInfoBox(WOContext context) {
    super(context);
  }

}