package fr.univlr.cri.conges;
// Generated by the WOLips Templateengine Plug-in at 24 mai 2007 09:20:02

import java.lang.reflect.InvocationTargetException;

import com.webobjects.appserver.*;

import com.webobjects.foundation.*;
import com.webobjects.woextensions.*;

import fr.univlr.cri.conges.Application;
import fr.univlr.cri.conges.Session;
import fr.univlr.cri.conges.print.CngPdfBoxCtrl;
import fr.univlr.cri.util.StringCtrl;


/**
 This class and the associated component creates a simple long request page.
 This page takes the information from the main page and performs the calculation
 of the prime numbers.  Note that for a long request a developer must inherit
 from the WOLongResponse page and, in this case, implement methods for the 
 long task, the refresh rate, and the task to perform when the long request is
 complete.
 */
 
/**
 * Page d'attente pour la creation d'un document PDF via SIX. 
 *  
 * @author Cyril Tarade <cyril.tarade at univ-lr.fr>
 */

public class CngPdfBoxComponent extends WOLongResponsePage {
  
	private static final double REFRESH_INTERVAL = 2.0;

	/** le flux PDF une fois genere */
	private NSData lastPdfData;
	
	/** le controleur d'impression */
	private CngPdfBoxCtrl currentCtrl;

	/**
	 * Constructor - initializes the instance variables to default
	 * values, which will be overridden by the passed in arguments.  This
	 * is done to ensure that if any are not set by the arguments the example
	 * can continue.
	 */
	public CngPdfBoxComponent(WOContext context) {
		super(context);
		lastPdfData = null;
		setRefreshInterval(REFRESH_INTERVAL);
		setCachingEnabled(false);
	}
	
	/**
	 * Override of appendToResponse - this method increments the count (the total
	 * number of refreshes) and sets the refresh interval to the passed in
	 * value.
	 */
	public void appendToResponse(WOResponse aResponse, WOContext aContext) {
		setRefreshInterval(REFRESH_INTERVAL);
		super.appendToResponse( aResponse, aContext );
	}


	/**
	 * Override of performAction method - this is where the main computation is done
	 * for the example.  By placing the computation in invokeAction is is automatically
	 * performed when the component loads.  Here we use the current values of the
	 * start and stop values to calculate all of the primes.
	 */
	public Object performAction() {
		PrintFactory printFactory = new PrintFactory();
		/* This class does a setStatus: on the refresh page as it is computing
		 * another way of setting the status would be to implement
		 * -returnStatusPage, and in there, to have the main thread pole this object
		 * (first keep this object as an ivar) for the status.
		 * but then pnc needs a thread safe -status method.
		 */
		printFactory.doPrint();
		return null;
	}
	
	private Application cngApp() {
		return (Application)Application.application();
	}
	
	private Session cngSession() {
		return (Session)session();
	}

	/**
	 * Method to return the result page when the computation is complete.  This
	 * methods sets the result page, passes all of the computation information,
	 * and then returns the page.
	 */
	public WOComponent pageForResult(Object result) {
		return null;
		//return getPdfPage();
	}

	/**
	 * Il est possible que la page ne bascule pas automatiquement
	 * vers le contenu fichier PDF. Si c'est le cas, on propose
	 * un acces manuel.
	 */
	public WOComponent getPdfPage() {
		((Session)session()).setCurrentPdfData(lastPdfData);
		((Session)session()).setCurrentPdfCtrl(currentCtrl());
		String url = cngApp().getApplicationURL(context())+"/wa/print?wosid="+cngSession().sessionID();
		WORedirect redirect = new WORedirect(context());
		redirect.setUrl(url);
		return redirect;
	}
	
	/**
	 * La classe qui fait le boulot
	 */
	private class PrintFactory {
		public void doPrint() {
			isWorking = true;
			lastPdfData = null;
			try {
				lastPdfData = currentCtrl().generatePdfData();
			} catch (SecurityException e) {
				e.printStackTrace();
			} catch (IllegalArgumentException e) {
				e.printStackTrace();
			} catch (NoSuchMethodException e) {
				e.printStackTrace();
			} catch (InstantiationException e) {
				e.printStackTrace();
			} catch (IllegalAccessException e) {
				e.printStackTrace();
			} catch (InvocationTargetException e) {
				e.printStackTrace();
			} finally {
				isWorking = false;
			}
		}		
  }
	
	/**
	 * Indique si la construction du dico des donnees est terminee
	 */
	public boolean isDicoOver() {
		return currentCtrl().getTimeDico() != null;
	}
	
	/**
	 * Indique si la construction du fichier XML est terminee
	 */
	public boolean isXmlOver() {
		return currentCtrl().getTimeXml() != null;
	}
	
	/**
	 * Indique si la generation du PDF par SIX est terminee
	 */
	public boolean isSixOver() {
		return currentCtrl().getTimeSix() != null;
	}
	
	/**
	 * Indique si la generation du PDF par SIX a echoue
	 */
	public boolean isErrSix() {
		return currentCtrl().isErrSix();
	}

	/**
	 * Indique si le message d'erreur si SIX est en erreur
	 */
	public String getStrErrSix() {
		return currentCtrl().getErrSix();
	}
	
	/**
	 * Indique s'il faut afficher un message a la fin de l'edition
	 * @return
	 */
	public boolean hasEndingMessage() {
		return !StringCtrl.isEmpty(getEndingMessage());
	}
	
	/**
	 * Indique si le message de fin de traitement
	 */
	public String getEndingMessage() {
		return currentCtrl().getEndingMessage();
	}
	
	/**
	 * Indique si la production du dico est en cours
	 */
	public boolean isDicoStep() {
		return !isDicoOver();
	}
	
	/**
	 * Indique si la production du dico est en cours
	 */
	public boolean isXmlStep() {
		return isDicoOver() && !isXmlOver();
	}
	
	/**
	 * Indique si la production du dico est en cours
	 */
	public boolean isSixStep() {
		return isXmlOver() && !isSixOver();
	}

	/**
	 * Le temps de calcul du dico.
	 * Si termine -> la valeur du controleur
	 * Si en cours : date debut d'execution du controleur - date actuelle
	 */
	public String timeExecDico() {
		Number result = null;
		if (isDicoOver()) {
			result = new Float(currentCtrl().getTimeDico().floatValue()/1000.0);
		} else {
			if (isDicoStep()) {
				if (currentCtrl().getTimeStart() == null) {
					result = new Float(0);
				} else {
					result = new Float((System.currentTimeMillis()-currentCtrl().getTimeStart().longValue())/1000.0);
				}
			} else {
				result = new Float(0);
			}
		}	
		return numberFormatter().format(result);
	}
	
	/**
	 * Le temps de calcul du XML.
	 * Si termine -> la valeur du controleur
	 * Si en cours : date debut d'execution du controleur - date dico
	 * Si pas termine : 0
	 */
	public String timeExecXml() {
		Number result = null;
		if (isXmlOver()) {
			result = new Float(currentCtrl().getTimeXml().floatValue()/1000.0);
		} else {
			if (isXmlStep()) {
				result = new Float((System.currentTimeMillis()-currentCtrl().getTimeDico().longValue()-currentCtrl().getTimeStart().longValue())/1000.0);
			} else {
				result = new Float(0);
			}
		}
		return numberFormatter().format(result);
	}
	
	/**
	 * Le temps de calcul du SIX.
	 * Si termine -> la valeur du controleur
	 * Si en cours : date debut d'execution du controleur - (duree dico + xml)
	 * Si pas termine : 0
	 */
	public String timeExecSix() {
		Number result = null;
		if (isSixOver()) {
			result = new Float(currentCtrl().getTimeSix().floatValue()/1000.0);
		} else {
			if (isSixStep()) {
				result = new Float((System.currentTimeMillis()
						- (currentCtrl().getTimeXml().longValue()+currentCtrl().getTimeDico().longValue())
						- currentCtrl().getTimeStart().longValue())/1000);
			} else {
				result = new Float(0);
			}
		}
		return numberFormatter().format(result);
	}
	
	/**
	 * Affichage des durees
	 */
	private NSNumberFormatter numberFormatter;
	
	public NSNumberFormatter numberFormatter() {
		if (numberFormatter == null) {
			numberFormatter = new NSNumberFormatter();
		  numberFormatter.setPattern("#,##0.00 s");
		  numberFormatter.setHasThousandSeparators(true);
		  numberFormatter.setThousandSeparator(" ");
		}
		return numberFormatter;
	}
	
	/**
	 * 
	 */
	public void setCurrentCtrl(CngPdfBoxCtrl value) {
		currentCtrl = value;
	}
	
	/**
	 * 
	 */
	public CngPdfBoxCtrl currentCtrl() {
		return currentCtrl;
	}

	private static boolean isWorking = false;
	
	public boolean isWorking() {
		return isWorking;
	}

	public String getFileName() {
		return currentCtrl().dateFileName() + ".pdf";
	}
}