package fr.univlr.cri.conges;
// Generated by the WOLips TemplateEngine Plug-in at 29 mai 2006 15:37:59

import com.webobjects.appserver.*;

/**
 * Composant permettant d'ouvrir une popup a partir d'un lien
 * sur le planning
 * @author Cyril TARADE <cyril.tarade at univ-lr.fr>
 */

public class LnkCngPopup extends WOComponent {

  // Les noms des connecteurs.
  private final String BND_LNK_TEXT      = "lnkText";  
  private final String BND_ACTION        = "action";
  private final String BND_HEIGHT        = "height";
  private final String BND_DISABLED      = "disabled";
  private final String BND_TITLE         = "title";
  
  public LnkCngPopup(WOContext context) {
    super(context);
  }

  /*
   * @see com.webobjects.appserver.WOComponent#synchronizesVariablesWithBindings()
   */
  public boolean synchronizesVariablesWithBindings() {
    return false;
  }
  
  /**
   * L'action WebObjects a appeler lors du clic dans la fenetre
   */
  public WOComponent action() {
    if (valueForBinding(BND_ACTION) != null)
      return (WOComponent) valueForBinding(BND_ACTION);
    return null;
  }

  
  /**
   * 
   */
  public String lnkText() {
    if (valueForBinding(BND_LNK_TEXT) != null)
      return (String) valueForBinding(BND_LNK_TEXT);
    return "????";
  }

  /**
   * 
   */
  public Integer height() {
    if (valueForBinding(BND_HEIGHT) != null)
      return (Integer) valueForBinding(BND_HEIGHT);
    return new Integer(400);
  }
  
  /**
   * 
   */
  public Boolean disabled() {
    if (valueForBinding(BND_DISABLED) != null)
      return (Boolean) valueForBinding(BND_DISABLED);
    return Boolean.FALSE;
  }
  
  /**
   * 
   */
  public String title() {
    if (valueForBinding(BND_TITLE) != null)
      return (String) valueForBinding(BND_TITLE);
    return "";
  }

}