package fr.univlr.cri.conges;
// Generated by the WOLips TemplateEngine Plug-in at 23 ao�t 2005 15:23:28

import com.webobjects.appserver.*;
import com.webobjects.foundation.NSArray;

import fr.univlr.cri.conges.eos.modele.grhum.EOIndividu;
import fr.univlr.cri.webapp.LRLog;

public class PageChangeIdentite extends YCRIWebPage {

  public String nomPrenom;
  
  public NSArray lesIndividus;
  public EOIndividu unIndividu;
  public EOIndividu lIndividuSelectionne;
  
  public PageChangeIdentite(WOContext context) {
    super(context);
  }

  /**
   * connecte l'individu selectionne (CAS reste sur le login de l'ancienne personne)
   */
  public WOComponent prendreIdentite() {
    if (lIndividuSelectionne != null) {
    	LRLog.log("change identity : "+laSession.individuConnecte().nomComplet() + " > " +
    			lIndividuSelectionne.nomComplet());
      return laSession.loginRedirect(lIndividuSelectionne.persId());
    }
    return neFaitRien();
  }
  
 
}