package fr.univlr.cri.conges;
// Generated by the WOLips Core at Sun Aug 29 19:31:04 CEST 2004

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

import fr.univlr.cri.conges.PagePlannings;
import fr.univlr.cri.conges.eos.modele.planning.EOOccupation;

/**
 * Page de confirmation qu'une operation a été réalisée.
 * Peut afficher une edition de demande de conge papier.
 * 
 * @author ctarade
 */
public class PageTransactionOK 
	extends A_PagePrintDemCongePapier {

  public PageTransactionOK(WOContext context) {
    super(context);
  }

  public WOComponent fermerLaFenetre() {
  	WOComponent nextPage = laSession.getSavedPageWithName(PagePlannings.class.getName());
    return nextPage;
  }
  
  /**
   * Forcer le refresh de la page appelante en javascript.
   * Le code a executer depend fortement du navigateur !
   */
  public String btnFermerOnClick() {
    StringBuffer code = new StringBuffer();
    code.append("window.setTimeout('window.close()',200);return false;");
    code.insert(0, "FormFermerLaFenetre.submit();");
    return code.toString();
  }

  // edition de la demande papier
  
  private EOOccupation _recOccupationAImprimer;
  
  /**
   * Permet de forcer la valeur de l'occupation a imprimer si necessaire
   * @param value
   * @return
   */
	public void setRecOccupationAImprimer(EOOccupation value) {
		_recOccupationAImprimer = value;
	}
  
	public EOOccupation recOccupationAImprimer() {
		return _recOccupationAImprimer;
	}
  
  
  
}