package fr.univlr.cri.conges;

// Generated by the WOLips Core at Sat Sep 04 14:16:40 CEST 2004

import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOResponse;
import com.webobjects.foundation.NSArray;

import fr.univlr.cri.conges.constantes.ConstsMenu;

public class PageAdministration extends YCRIWebPage {

	// gestion du menu
	public class PageAdministrationSubMenuCtrl extends A_SubMenuCtrl {

		/**
		 * Les fonctionnalites disponibiltes disponibles different selon le type
		 * d'administrateur
		 */
		public NSArray labelList() {
			if (cngUserInfo().isAdmin()) {
				return ConstsMenu.MENU_ITEMS_ADMINISTRATION_ADMIN_GLOBAL;
			} else if (cngUserInfo().isAdmComposante()) {
				return ConstsMenu.MENU_ITEMS_ADMINISTRATION_ADMIN_COMPOSANTE;
			} else if (cngUserInfo().isDrh()) {
				return ConstsMenu.MENU_ITEMS_ADMINISTRATION_DRH_GLOBAL;
			} else {
				return new NSArray();
			}
		}

		public NSArray tipList() {
			if (cngUserInfo().isAdmin()) {
				return ConstsMenu.PAGE_ADMINISTRATION_ADMIN_GLOBAL_MENU_TIP_LIST;
			} else if (cngUserInfo().isAdmComposante()) {
				return ConstsMenu.PAGE_ADMINISTRATION_ADMIN_COMPOSANTE_MENU_TIP_LIST;
			} else if (cngUserInfo().isDrh()) {
				return ConstsMenu.PAGE_ADMINISTRATION_DRH_GLOBAL_MENU_TIP_LIST;
			} else {
				return new NSArray();
			}
		}

		public boolean isAdminOutils() {
			return getLabelSelected().equals(ConstsMenu.MENU_ADMIN_OUTILS);
		}

		public boolean isAdminDroits() {
			return getLabelSelected().equals(ConstsMenu.MENU_ADMIN_DROITS);
		}

		public boolean isDRHFermetures() {
			return getLabelSelected().equals(ConstsMenu.MENU_ADMIN_SUPP_FER);
		}

		public boolean isAdminCET() {
			return getLabelSelected().equals(ConstsMenu.MENU_ADMIN_CET);
		}

		public boolean isAdminDivers() {
			return getLabelSelected().equals(ConstsMenu.MENU_ADMIN_DIVERS_LABEL);
		}

		public boolean isAdminJrti() {
			return getLabelSelected().equals(ConstsMenu.MENU_ADMIN_JRTI);
		}

		public boolean isAdminSuivi() {
			return getLabelSelected().equals(ConstsMenu.MENU_ADMIN_SUIVI_LABEL);
		}

		public boolean isAdminParametres() {
			return getLabelSelected().equals(ConstsMenu.MENU_ADMIN_PARAMETRE);
		}

	}

	public PageAdministrationSubMenuCtrl pageAdministrationSubMenuCtrl;

	public PageAdministration(WOContext context) {
		super(context);
		pageAdministrationSubMenuCtrl = new PageAdministrationSubMenuCtrl();
	}

	public void appendToResponse(WOResponse arg0, WOContext arg1) {
		super.appendToResponse(arg0, arg1);
		// definit la css pour l'adminstration
		addLocalCss(arg0, "css/Admin.css");
	}

}