package fr.univlr.cri.conges;
// Generated by the WOLips TemplateEngine Plug-in at ${WOLipsContext.getDate()}

import com.webobjects.appserver.*;

import fr.univlr.cri.conges.YCRIWebPage;
import fr.univlr.cri.conges.objects.HoraireHebdomadaire;
import fr.univlr.cri.conges.objects.Planning;

public class PageLegende extends YCRIWebPage {
	
    public Planning lePlanning = laSession.getLePlanningSelectionne(); 

    public HoraireHebdomadaire unHoraireHebdomadaire;
    
    public PageLegende(WOContext context) {
        super(context);
    }

    public void appendToResponse(WOResponse arg0, WOContext arg1) {
      super.appendToResponse(arg0, arg1);
      // la css pour avoir la couleur des jours du planning
      addLocalCss(arg0, "css/Planning.css");
    }
    
    public String styles() {
      String styles = app.config().stringForKey("APP_HTML_CSS_STYLES");
      return styles;
    }
    
}