package fr.univlr.cri.conges;
// Generated by the WOLips Core at Fri Oct 24 13:08:23 GMT 2003

import com.webobjects.appserver.*;

public class ZCRILookupField extends WOComponent {

	public String filterText;

	public ZCRILookupField(WOContext context) {
		super(context);
	}
	public boolean synchronizesVariablesWithBindings() {
		return false;
	}
	
	public String connectionString() {
		return "<SCRIPT TYPE=\"text/javascript\" language=\"javascript\"><!--\n var filt"+ selectName() +"=new filterlist(document."+ formName() +"."+ selectName()  +");\n"
		+"filt"+ selectName() +".set(document."+ formName() +"."+ fieldName() +".value);"
		+"\n//-->\n</SCRIPT>";
	}
	
	public String onKeyUp() {
		return "javascript:filt"+ selectName() +".set(this.value);";
	}
	
	private String fieldName() {
		return (String) valueForBinding("fieldName");
	}
	private String formName() {
		return (String) valueForBinding("formName");
	}
	private String selectName() {
		return (String) valueForBinding("selectName");
	}
	
}