--
-- Patch DDL de CONGES du 07/07/2011 à éxecuter depuis le user GRHUM
--
-- Rem : fichier encodé UTF-8


SET DEFINE OFF;

--
--
-- Fichier : 1
-- Type : DDL
-- Schéma : CONGES
-- Numéro de version : 2.10.6
-- Date de publication : 07/07/2011
-- Auteur(s) : Cyril TARADE
-- Licence : CeCILL version 2
--
--


--
-- PLNG_TYP_OCC_PARAM  (Table) 
--
CREATE TABLE CONGES.PLNG_TYP_OCC_PARAM
(
  OID             NUMBER                        NOT NULL,
  OID_TYP_OCC     NUMBER                        NOT NULL,
  CONTRAINTE      VARCHAR2(32)                  NOT NULL,
  D_DEB_VALIDITE  DATE,
  D_FIN_VALIDITE  DATE,
  D_CREATION      DATE                          DEFAULT SYSDATE               NOT NULL,
  D_MODIFICATION  DATE                          DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CONGES.PLNG_TYP_OCC_PARAM IS 'Contraintes applicables à des types d''occupations : horaires forcés ...';

COMMENT ON COLUMN CONGES.PLNG_TYP_OCC_PARAM.OID IS 'Clé primaire';

COMMENT ON COLUMN CONGES.PLNG_TYP_OCC_PARAM.OID_TYP_OCC IS 'Type d''occupation concerné (table CONGES.PLNG_TYP_OCC)';

COMMENT ON COLUMN CONGES.PLNG_TYP_OCC_PARAM.CONTRAINTE IS 'Code de la contrainte ("HORAIRE_FORCE" ...)';

COMMENT ON COLUMN CONGES.PLNG_TYP_OCC_PARAM.D_DEB_VALIDITE IS 'Date de début d''application de la contrainte';

COMMENT ON COLUMN CONGES.PLNG_TYP_OCC_PARAM.D_FIN_VALIDITE IS 'Date de fin d''application de la contrainte';

COMMENT ON COLUMN CONGES.PLNG_TYP_OCC_PARAM.D_CREATION IS 'Date de création de l''enregistrement (interne)';

COMMENT ON COLUMN CONGES.PLNG_TYP_OCC_PARAM.D_MODIFICATION IS 'Date de dernière modification de l''enregistrement (interne)';


-- 
-- Non Foreign Key Constraints for Table PLNG_TYP_OCC_PARAM 
-- 
ALTER TABLE CONGES.PLNG_TYP_OCC_PARAM ADD (
  CONSTRAINT CHK_PTO_PARAM_CONTRAINTE
 CHECK (CONTRAINTE IN ('HORAIRE_FORCE'/*, 'FLG_DRH', 'CONGE_LEGAL'*/)),
  CONSTRAINT PK_PTO_PARAMETRE
 PRIMARY KEY
 (OID));

-- 
-- Foreign Key Constraints for Table PLNG_TYP_OCC_PARAM 
-- 
ALTER TABLE CONGES.PLNG_TYP_OCC_PARAM ADD (
  CONSTRAINT FK_PTO_PARAM_TYP_OCC 
 FOREIGN KEY (OID_TYP_OCC) 
 REFERENCES CONGES.PLNG_TYP_OCC (OID));


CREATE SEQUENCE CONGES.PLNG_TYP_OCC_PARAM_SEQ NOCACHE;


-- bascule des contraintes vers la nouvelle table
INSERT INTO CONGES.PLNG_TYP_OCC_PARAM
    (OID, OID_TYP_OCC, CONTRAINTE, D_DEB_VALIDITE, D_FIN_VALIDITE)  
SELECT
    CONGES.PLNG_TYP_OCC_PARAM_SEQ.NEXTVAL, OID, 'HORAIRE_FORCE',
    NULL, NULL
FROM CONGES.PLNG_TYP_OCC
WHERE HORAIRE_FORCE = 1;


/*
INSERT INTO CONGES.PLNG_TYP_OCC_PARAM
    (OID, OID_TYP_OCC, CONTRAINTE, D_DEB_VALIDITE, D_FIN_VALIDITE)  
SELECT
    CONGES.PLNG_TYP_OCC_PARAM_SEQ.NEXTVAL, OID, 'CONGE_LEGAL',
    NULL, NULL
FROM CONGES.PLNG_TYP_OCC
WHERE CONGE_LEGAL = 1;

INSERT INTO CONGES.PLNG_TYP_OCC_PARAM
    (OID, OID_TYP_OCC, CONTRAINTE, D_DEB_VALIDITE, D_FIN_VALIDITE)  
SELECT
    CONGES.PLNG_TYP_OCC_PARAM_SEQ.NEXTVAL, OID, 'FLG_DRH',
    NULL, NULL
FROM CONGES.PLNG_TYP_OCC
WHERE FLG_DRH = 1;*/

ALTER TABLE CONGES.PLNG_TYP_OCC DROP COLUMN HORAIRE_FORCE;

INSERT INTO CONGES.DB_VERSION ( DB_VERSION_ID, DB_VERSION_LIBELLE, DB_VERSION_DATE, DB_INSTALL_DATE,DB_COMMENT ) VALUES 
	( 2106, '2.10.6',  TO_DATE( '07/07/2011', 'DD/MM/YYYY'),  SYSDATE, 'Base de donnees CONGES v2.10.6'); 



COMMIT;

